# Generated by Django 5.1.6 on 2025-06-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='nome_Produto',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='tipo',
        ),
        migrations.AddField(
            model_name='produtos',
            name='perecivel',
            field=models.BooleanField(default=False),
        ),
    ]
